/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  name: string;
  slug: string;
  layout?:
    | (
        | {
            title?: string | null;
            description?: string | null;
            backgroundImage?: (number | null) | Media;
            images?: {
              image1?: (number | null) | Media;
              image2?: (number | null) | Media;
              image3?: (number | null) | Media;
              image4?: (number | null) | Media;
              image5?: (number | null) | Media;
              image6?: (number | null) | Media;
            };
            buttonGroup?: {
              aboutButton?: {
                label?: string | null;
                url?: string | null;
              };
              priceButton?: {
                label?: string | null;
                url?: string | null;
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            heading?: string | null;
            description?: string | null;
            subheading1?: string | null;
            subcontent1?: string | null;
            subheading2?: string | null;
            subcontent2?: string | null;
            images?: {
              image1?: (number | null) | Media;
              image2?: (number | null) | Media;
              image3?: (number | null) | Media;
              image4?: (number | null) | Media;
            };
            bgImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textAndFourImages';
          }
        | {
            headingGroup?: {
              heading?: string | null;
              headingSpan?: string | null;
            };
            description: string;
            images?:
              | {
                  image: number | Media;
                  alt?: string | null;
                  services?: string | null;
                  servicesDescription?: string | null;
                  id?: string | null;
                }[]
              | null;
            button: {
              label: string;
              url: string;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'threeByThreeContent';
          }
        | {
            headingGroup?: {
              heading?: string | null;
              headingSpan?: string | null;
              headingDescription?: string | null;
            };
            subheadingGroup1?: {
              subheading?: string | null;
              subheadingDescription?: string | null;
              subheadingLogo?: (number | null) | Media;
            };
            subheadingGroup2?: {
              subheading?: string | null;
              subheadingDescription?: string | null;
              subheadingLogo?: (number | null) | Media;
            };
            subheadingGroup3?: {
              subheading?: string | null;
              subheadingDescription?: string | null;
              subheadingLogo?: (number | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'whyUs';
          }
        | {
            headingGroup?: {
              heading?: {
                heading0?: string | null;
                headingSpan1?: string | null;
                headingSpan2?: string | null;
                headingSpan3?: string | null;
              };
              headingDescription?: string | null;
            };
            images?:
              | {
                  image: number | Media;
                  alt?: string | null;
                  completeExpertName?: string | null;
                  expertDescription?: string | null;
                  id?: string | null;
                }[]
              | null;
            CTAButton?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentCarousel';
          }
        | {
            title?: string | null;
            bgImage?: (number | null) | Media;
            cardGroupArray?:
              | {
                  cardGroup?: {
                    fullName?: string | null;
                    profession?: string | null;
                    thoughts?: string | null;
                    picture?: (number | null) | Media;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'CardAndImage';
          }
        | {
            title?: {
              titleSpan1?: string | null;
              titleSpan2?: string | null;
            };
            description?: string | null;
            subDescription?: string | null;
            images?:
              | {
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'realisationsCarousel';
          }
        | {
            title?: string | null;
            description?: string | null;
            questionsArray?:
              | {
                  question?: string | null;
                  answer?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqComponent';
          }
        | {
            title?: string | null;
            logo?: (number | null) | Media;
            certificationArray?:
              | {
                  textContent?: string | null;
                  textSubContent?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'certificationSection';
          }
        | {
            nameInput?: {
              label?: string | null;
              placeholder?: string | null;
            };
            mailInput?: {
              label?: string | null;
              placeholder?: string | null;
            };
            serviceInput?: {
              label?: string | null;
              placeholder?: string | null;
            };
            houseTypeInput?: {
              label?: string | null;
              placeholder?: string | null;
            };
            dateInput?: {
              label?: string | null;
            };
            otherInput?: {
              label?: string | null;
              placeholder?: string | null;
            };
            detailsInput?: {
              label?: string | null;
              placeholder?: string | null;
            };
            checkboxLabel?: string | null;
            buttonGroup?: {
              label?: string | null;
              url?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'bookingForm';
          }
        | {
            title?: string | null;
            description?: string | null;
            firstName?: {
              label?: string | null;
              placeholder?: string | null;
            };
            lastName?: {
              label?: string | null;
              placeholder?: string | null;
            };
            select?:
              | {
                  label?: string | null;
                  placeholder?: string | null;
                  selections?:
                    | {
                        selection?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            mail?: {
              label?: string | null;
              placeholder?: string | null;
            };
            descriptionInput?: {
              label?: string | null;
              placeholder?: string | null;
            };
            button?: {
              label?: string | null;
              url?: string | null;
            };
            consentText?: {
              prefix?: string | null;
              termsLabel?: {
                texte?: string | null;
                url?: string | null;
              };
              andSeparator?: string | null;
              privacyLabel?: {
                texte?: string | null;
                url?: string | null;
              };
            };
            copyrightNotice?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteForm';
          }
        | {
            title?: string | null;
            description?: string | null;
            firstName?: {
              label?: string | null;
              placeholder?: string | null;
            };
            lastName?: {
              label?: string | null;
              placeholder?: string | null;
            };
            select?:
              | {
                  label?: string | null;
                  placeholder?: string | null;
                  selections?:
                    | {
                        selection?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            mail?: {
              label?: string | null;
              placeholder?: string | null;
            };
            descriptionInput?: {
              label?: string | null;
              placeholder?: string | null;
            };
            button?: {
              label?: string | null;
              url?: string | null;
            };
            consentText?: {
              prefix?: string | null;
              termsLabel?: {
                texte?: string | null;
                url?: string | null;
              };
              andSeparator?: string | null;
              privacyLabel?: {
                texte?: string | null;
                url?: string | null;
              };
            };
            copyrightNotice?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              description?: T;
              backgroundImage?: T;
              images?:
                | T
                | {
                    image1?: T;
                    image2?: T;
                    image3?: T;
                    image4?: T;
                    image5?: T;
                    image6?: T;
                  };
              buttonGroup?:
                | T
                | {
                    aboutButton?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    priceButton?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        textAndFourImages?:
          | T
          | {
              heading?: T;
              description?: T;
              subheading1?: T;
              subcontent1?: T;
              subheading2?: T;
              subcontent2?: T;
              images?:
                | T
                | {
                    image1?: T;
                    image2?: T;
                    image3?: T;
                    image4?: T;
                  };
              bgImage?: T;
              id?: T;
              blockName?: T;
            };
        threeByThreeContent?:
          | T
          | {
              headingGroup?:
                | T
                | {
                    heading?: T;
                    headingSpan?: T;
                  };
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    services?: T;
                    servicesDescription?: T;
                    id?: T;
                  };
              button?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whyUs?:
          | T
          | {
              headingGroup?:
                | T
                | {
                    heading?: T;
                    headingSpan?: T;
                    headingDescription?: T;
                  };
              subheadingGroup1?:
                | T
                | {
                    subheading?: T;
                    subheadingDescription?: T;
                    subheadingLogo?: T;
                  };
              subheadingGroup2?:
                | T
                | {
                    subheading?: T;
                    subheadingDescription?: T;
                    subheadingLogo?: T;
                  };
              subheadingGroup3?:
                | T
                | {
                    subheading?: T;
                    subheadingDescription?: T;
                    subheadingLogo?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contentCarousel?:
          | T
          | {
              headingGroup?:
                | T
                | {
                    heading?:
                      | T
                      | {
                          heading0?: T;
                          headingSpan1?: T;
                          headingSpan2?: T;
                          headingSpan3?: T;
                        };
                    headingDescription?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    alt?: T;
                    completeExpertName?: T;
                    expertDescription?: T;
                    id?: T;
                  };
              CTAButton?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        CardAndImage?:
          | T
          | {
              title?: T;
              bgImage?: T;
              cardGroupArray?:
                | T
                | {
                    cardGroup?:
                      | T
                      | {
                          fullName?: T;
                          profession?: T;
                          thoughts?: T;
                          picture?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        realisationsCarousel?:
          | T
          | {
              title?:
                | T
                | {
                    titleSpan1?: T;
                    titleSpan2?: T;
                  };
              description?: T;
              subDescription?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqComponent?:
          | T
          | {
              title?: T;
              description?: T;
              questionsArray?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        certificationSection?:
          | T
          | {
              title?: T;
              logo?: T;
              certificationArray?:
                | T
                | {
                    textContent?: T;
                    textSubContent?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        bookingForm?:
          | T
          | {
              nameInput?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              mailInput?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              serviceInput?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              houseTypeInput?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              dateInput?:
                | T
                | {
                    label?: T;
                  };
              otherInput?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              detailsInput?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              checkboxLabel?: T;
              buttonGroup?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quoteForm?:
          | T
          | {
              title?: T;
              description?: T;
              firstName?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              lastName?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              select?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                    selections?:
                      | T
                      | {
                          selection?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              mail?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              descriptionInput?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              button?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              consentText?:
                | T
                | {
                    prefix?: T;
                    termsLabel?:
                      | T
                      | {
                          texte?: T;
                          url?: T;
                        };
                    andSeparator?: T;
                    privacyLabel?:
                      | T
                      | {
                          texte?: T;
                          url?: T;
                        };
                  };
              copyrightNotice?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              title?: T;
              description?: T;
              firstName?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              lastName?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              select?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                    selections?:
                      | T
                      | {
                          selection?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              mail?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              descriptionInput?:
                | T
                | {
                    label?: T;
                    placeholder?: T;
                  };
              button?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              consentText?:
                | T
                | {
                    prefix?: T;
                    termsLabel?:
                      | T
                      | {
                          texte?: T;
                          url?: T;
                        };
                    andSeparator?: T;
                    privacyLabel?:
                      | T
                      | {
                          texte?: T;
                          url?: T;
                        };
                  };
              copyrightNotice?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}